name: 'AWS Cloudformation - SAM Deploy Action'
description: 'AWS Cloudformation - Deploy AWS SAM Stack'
branding:
  icon: 'cloud-lightning'
  color: 'orange'
runs:
  using: 'docker'
  image: 'Dockerfile'
